apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: omb7tzsuz-java-quarkus 
  janus-idp.io/tekton: omb7tzsuz-java-quarkus
  backstage.io/kubernetes-id: omb7tzsuz-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: omb7tzsuz-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml